---
title: "Blischak Data EDA"
author: "David Gerard"
date: "June 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Here, I try out some EDA on the Blischak data. I want to see if overdispersion, read-mapping bias, and outliers are still relevant.

# See if read-mapping bias is a problem.

Read in data.
```{r}
ocount_mat <- read.table("~/Code/polyploid-genotyping/data/c20-pubescens-refReads.txt")
osize_mat <- read.table("~/Code/polyploid-genotyping/data/c20-pubescens-totReads.txt")
```


It's super low coverage! It's impossible to see the aspects of the data that I found so important.

```{r}
library(updog)
order_vec <- order(colSums(osize_mat), decreasing = TRUE)

for (index in 1:10) {
  ocounts <- ocount_mat[, order_vec[index]]
  osize <- osize_mat[, order_vec[index]]
  ocounts[ocounts == -9] <- NA
  osize[osize == -9] <- NA
  print(plot_geno(ocounts = ocounts, osize = osize, ploidy = 4))
}
```


```{r}
sessionInfo()
```
