---
title: "Try out HW for the first time"
author: "David Gerard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Here, I try out the Hardy-Weinberg fits for `updog` for the first time.

# Analysis

Read in data:

```{r}
library(updog)
library(tidyverse)
load("../data/subset_David.Rdata")
ploidy <- 6

dat_list <- list()
for (col in 1:length(subset_david)){
  dat <- as_data_frame(subset_david[[col]])
  dat$id <- rownames(subset_david[[col]])
  names(dat) <- c("A", "a", "id")
  dat <- dat %>% mutate(ocounts = A, osize = a + A)
  pdat <- filter(dat, grepl("Beauregard", id) | grepl("Tanzania", id))
  cdat <- filter(dat, !(grepl("Beauregard", id) | grepl("Tanzania", id)))
  dat_list[[col]] <- cdat
  print(sort(dat$osize)[1:5])
}
```


Fit `updog` both with HW and with F1.

```{r}
index <- 7

dat <- dat_list[[index]]

uf1 <- updog_vanilla(ocounts = dat$ocounts, osize = dat$osize, ploidy = 6,
                     model = "f1", print_val = TRUE)
uhw <- updog_vanilla(ocounts = dat$ocounts, osize = dat$osize, ploidy = 6,
                     model = "hw", print_val = TRUE)

plot(uf1, plot_beta = FALSE)
plot(uhw, plot_beta = FALSE)
```



```{r}
sessionInfo()
```
