---
title: "First Fits with Outlier Model"
author: "First Last"
date: "`r Sys.Date()`"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

Here, I try out vanilla updog with the outlier model.

## Read in Data

I am going to choose one that shows some bias and some outliers.

```{r}
library(updog)
set.seed(483)
load("../data/subset_David.Rdata")
ddat <- subset_david
lastp <- 12 ## number of final rows that are parents

cmat <- ddat[[10]]
p1dat <- cmat[(nrow(cmat) - lastp + 1):(nrow(cmat) - lastp / 2), ]
p2dat <- cmat[(nrow(cmat) - lastp / 2 + 1):nrow(cmat), ]
odat  <- cmat[1:(nrow(cmat) - lastp), ]

p1counts <- p1dat[, 1]
p1size   <- rowSums(p1dat)
p2counts <- p2dat[, 1]
p2size   <- rowSums(p2dat)
ocounts  <- odat[, 1]
osize    <- rowSums(odat)
ploidy <- 6
```

Raw plots

```{r}
plot_geno(ocounts = ocounts, osize = osize, ploidy = ploidy, seq_error = 0)
```


```{r, results="hide", message=FALSE}
uout <- updog_vanilla(ocounts = ocounts, osize = osize, ploidy = ploidy, print_val = FALSE)
geno_vec <- uout$ogeno
maxpostprob_vec <- uout$maxpost
```

Summarize data: The new lines look pretty great!

```{r}
library(tidyverse)
dat <- data_frame(A = ocounts, a = osize - ocounts, geno = factor(geno_vec), maxpostprob = maxpostprob_vec)

## get possible probabilities based on fits of updog
pvec <- updog::get_pvec(ploidy = ploidy, bias_val = uout$bias, seq_error = uout$seq_error)
pvec
slopevec <- pvec / (1 - pvec)
maxcount <- max(max(dat$A), max(dat$a))
xend <- pmin(rep(maxcount, ploidy + 1), maxcount / slopevec)
yend <- pmin(rep(maxcount, ploidy + 1), maxcount * slopevec)
df_lines <- data.frame(x = rep(0, ploidy + 1), y = rep(0, ploidy + 1),
                       xend = xend, yend = yend)
ggplot(data = dat, mapping = aes(x = a, y = A, color = geno, alpha = 1 - uout$prob_out)) +
  geom_point() +
  ylim(0, maxcount) +
  xlim(0, maxcount) +
  theme_bw() +
  geom_segment(data = df_lines, mapping = aes(x = x, y = y, xend = xend, yend = yend), lty = 2, alpha = 1/2,
               color = "black", size = 0.5)


```

All of the others. Original lines are in blue, new lines are in black. 

```{r, cache=TRUE}
for (index in 1:length(ddat)) {
  cmat <- ddat[[index]]
  p1dat <- cmat[(nrow(cmat) - lastp + 1):(nrow(cmat) - lastp / 2), ]
  p2dat <- cmat[(nrow(cmat) - lastp / 2 + 1):nrow(cmat), ]
  odat  <- cmat[1:(nrow(cmat) - lastp), ]

  p1counts <- p1dat[, 1]
  p1size   <- rowSums(p1dat)
  p2counts <- p2dat[, 1]
  p2size   <- rowSums(p2dat)
  ocounts  <- odat[, 1]
  osize    <- rowSums(odat)
  ploidy <- 6

  uout <- updog_vanilla(ocounts = ocounts, osize = osize, ploidy = ploidy, print_val = FALSE)
  geno_vec <- uout$ogeno
  maxpostprob_vec <- uout$maxpostprob
  prob_ok <- 1 - uout$prob_out


  dat <- data_frame(A = ocounts, a = osize - ocounts, geno = factor(geno_vec), maxpostprob = maxpostprob_vec, prob_ok = prob_ok)
  pvec <- updog::get_pvec(ploidy = ploidy, bias_val = uout$bias, seq_error = uout$seq_error)
  pvec
  ## estimated slope
  slopevec <- pvec / (1 - pvec)
  maxcount <- max(max(dat$A), max(dat$a))
  xend <- pmin(rep(maxcount, ploidy + 1), maxcount / slopevec)
  yend <- pmin(rep(maxcount, ploidy + 1), maxcount * slopevec)
  df_lines <- data.frame(x = rep(0, ploidy + 1), y = rep(0, ploidy + 1),
                         xend = xend, yend = yend)
  
  
  ## original slope
  opvec <- 0:ploidy / ploidy
  slopevec <- opvec / (1 - opvec)
  maxcount <- max(max(dat$A), max(dat$a))
  xend <- pmin(rep(maxcount, ploidy + 1), maxcount / slopevec)
  yend <- pmin(rep(maxcount, ploidy + 1), maxcount * slopevec)
  odf_lines <- data.frame(x = rep(0, ploidy + 1), y = rep(0, ploidy + 1),
                          xend = xend, yend = yend)
  
  ## raw plot
  po <- plot_geno(ocounts = ocounts, osize = osize, ploidy = ploidy, seq_error = 0)
  print(po)
  ## fitted plot
  pl <- ggplot(data = dat, mapping = aes(x = a, y = A, color = geno, alpha = prob_ok)) +
    geom_point() +
    ylim(0, maxcount) +
    xlim(0, maxcount) +
    theme_bw() +
    geom_segment(data = df_lines, mapping = aes(x = x, y = y, xend = xend, yend = yend), lty = 2, alpha = 1/2,
                 color = "black", size = 0.5) +
    geom_segment(data = odf_lines, mapping = aes(x = x, y = y, xend = xend, yend = yend), lty = 3, alpha = 1/2,
                 color = "blue", size = 0.5)
  print(pl)
}
```

```{r info}
sessionInfo()
```
